# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
# Holder.create(location: "British Museum, London")
# Holder.create(location: "The National Gallery, London")
# Holder.create(location: "National Galleries of Scotland, Edinborough")
# Holder.create(location: "Courtauld Gallery, London")
# Holder.create(location: "Musée du Louvre, Paris")
# Holder.create(location: "Château de Versailles, Paris")
# Holder.create(location: "Le Petit Palais, Paris")
# Holder.create(location: "Musée d'Orsay, Paris")
# Holder.create(location: "Musée de l'Orangerie, Paris")
# Holder.create(location: "Musée de Cluny, Paris")
# Holder.create(location: "Musée Marmottan Monet, Paris")
# Holder.create(location: "Musée de Grenoble, Grenoble")
# Holder.create(location: "Musée des Beaux-Arts d'Orléans, Orléans")
# Holder.create(location: "Musée des Beaux-Arts de Nantes, Nantes")
# Holder.create(location: "Musée des Beaux-Arts de Nancy, Nancy")
# Holder.create(location: "Musée des Beaux-Arts de Dijon, Dijon")
# Holder.create(location: "Musée des Beaux-Arts de Reims, Reims")
# Holder.create(location: "Grand Palais, Paris")
# Holder.create(location: "Louvre Lens, Lens")
# Holder.create(location: "Domaine de Chantilly, Chantilly")
# Holder.create(location: "Staatliche Museen zu Berlin, Berlin")
# Holder.create(location: "Galleria degli Uffizi, Firenze")
# Holder.create(location: "Galleria Palatina, Palazzo Pitti, Firenze")
# Holder.create(location: "Galleria dell'Accademia, Firenze")
# Holder.create(location: "Vatican Museums, Vatican")
# Holder.create(location: "Museo Nacional del Prado, Madrid")
# Holder.create(location: "Museo Nacional de Arte de Cataluña, Barcelona")
# Holder.create(location: "Kunsthistorisches Museum, Wien")
# Holder.create(location: "National Gallery in Prague, Praha")
# Holder.create(location: "Muzeum Książąt Czartoryskich, Kraków")
# Holder.create(location: "The Pushkin State Museum of Fine Arts, Moscow")
# Holder.create(location: "The State Hermitage Museum, Saint Petersburg")
# Holder.create(location: "The Metropolitan Museum of Art, New York")
# Period.create(time_frame: "Stone Age")
# Period.create(time_frame: "Crete, Mycenae and Greek Art")
# Period.create(time_frame: "Etruscan")
# Period.create(time_frame: "Roman")
# Period.create(time_frame: "Early Christian")
# Period.create(time_frame: "Early Medieval")
# Period.create(time_frame: "Byzantine")
# Period.create(time_frame: "Romanesque")
# Period.create(time_frame: "Gothic")
# Period.create(time_frame: "International Gothic")
# Period.create(time_frame: "Early Renaissance")
# Period.create(time_frame: "Early Northern Renaissance")
# Period.create(time_frame: "High Renaissance")
# Period.create(time_frame: "Mannerism")
# Period.create(time_frame: "Northern Renaissance")
# Period.create(time_frame: "Baropue")
# Period.create(time_frame: "Rococo")
# Period.create(time_frame: "Neoclassical")
# Period.create(time_frame: "Romanticism")
# Period.create(time_frame: "Realism")
# Period.create(time_frame: "Symbolism")
# Period.create(time_frame: "Impressionism")
# Period.create(time_frame: "Post-Impressionism")
# Period.create(time_frame: "Art Nouveau")
# Period.create(time_frame: "20th Century Art")
# 以上20181022追加
